---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart watcher service
  ansible.builtin.systemd_service:
    name: "{{ watcher_systemd_service_name }}"
    state: restarted
  when: not ansible_check_mode
